version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # environment:
    #   ADMINER_DB: qor_example
    #   ADMINER_DRIVER: pgsql
    #   ADMINER_PASSWORD: adminer
    #   ADMINER_SERVER: db
    #   ADMINER_USERNAME: adminer
    #   ADMINER_AUTOLOGIN: 1
    #   ADMINER_NAME: This will be in the title!

  db:
    image: postgres:10.4
    restart: always
    environment:
      # POSTGRES_PASSWORD: example
      POSTGRES_DB: qor_example
      POSTGRES_USER: adminer
      POSTGRES_PASSWORD: adminer
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  qor:
    image: dfang/qor-example:latest
    # build:
    #   context: .
    command: ["./qor-example"]
    # command: ["./seeds"]
    # command: [ "go", "run", "config/db/seeds/main.go", "config/db/seeds/seeds.go" ]
    restart: always
    # environment:
    #   QOR_AWS_ACCESS_KEY_ID: AKIAI3Z7SFTABSJQSLDQ
    #   QOR_AWS_SECRET_ACCESS_KEY: secret
    #   QOR_AWS_BUCKET: qor-1234
    #   QOR_AWS_REGION: ap-northeast-1
    env_file:
      - .env
    volumes:
      - ./config/database.yml:/go-app/config/database.yml
    ports:
      - 7000:7000
